import { ApiCatalog } from './catalog';

function signature(method: { name: string; parameters?: { name: string; type?: string }[]; returnType?: string }): string {
  const parameters = (method.parameters || []).map((parameter) =>
    `${parameter.name}: ${parameter.type || 'any'}`).join(', ');
  return `- \`${method.name}(${parameters})${method.returnType ? `: ${method.returnType}` : ''}\``;
}

export function renderApiContext(catalog: ApiCatalog): string {
  const lines = [
    '# AUBO Lua API context',
    '',
    'Generated by the AUBO VS Code extension from the local authorized catalog.',
    'Use exact catalog names. Do not invent SDK functions or replace `moveJoint` with `moveJ`.',
    '',
    '## Script shape',
    '',
    '```lua',
    "local aubo = require('aubo')",
    'local sched = sched or aubo.sched',
    'local _ENV = sched.select_robot(1)',
    'moveJoint(target, acceleration, speed, blend, duration)',
    '```',
    '',
    `## Catalog ${catalog.interfaceVersion}${catalog.sdkVersion ? ` (SDK ${catalog.sdkVersion})` : ''}`,
    ''
  ];
  for (const module of catalog.modules) {
    const name = module.luaModule || module.name;
    lines.push(`### ${name}`, '');
    for (const property of module.properties || []) {
      lines.push(`- \`${property.name}${property.type ? `: ${property.type}` : ''}\`${property.description ? ` — ${property.description}` : ''}`);
    }
    for (const method of module.methods) lines.push(signature(method));
    lines.push('');
  }
  return `${lines.join('\n').trim()}\n`;
}
